//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifoneIntegration.Verifone {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="https://www.commidea.webservices.com")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VerifoneIntegration.Verifone.ClientHeader ClientHeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public VerifoneIntegration.Verifone.ClientHeader ClientHeader {
            get {
                return this.ClientHeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientHeaderField, value) != true)) {
                    this.ClientHeaderField = value;
                    this.RaisePropertyChanged("ClientHeader");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MsgType {
            get {
                return this.MsgTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgTypeField, value) != true)) {
                    this.MsgTypeField = value;
                    this.RaisePropertyChanged("MsgType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MsgData {
            get {
                return this.MsgDataField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgDataField, value) != true)) {
                    this.MsgDataField = value;
                    this.RaisePropertyChanged("MsgData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientHeader", Namespace="https://www.commidea.webservices.com")]
    [System.SerializableAttribute()]
    public partial class ClientHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal SystemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SystemGUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasscodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessingDBField;
        
        private int SendAttemptField;
        
        private bool CDATAWrappingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal SystemID {
            get {
                return this.SystemIDField;
            }
            set {
                if ((this.SystemIDField.Equals(value) != true)) {
                    this.SystemIDField = value;
                    this.RaisePropertyChanged("SystemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SystemGUID {
            get {
                return this.SystemGUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemGUIDField, value) != true)) {
                    this.SystemGUIDField = value;
                    this.RaisePropertyChanged("SystemGUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Passcode {
            get {
                return this.PasscodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PasscodeField, value) != true)) {
                    this.PasscodeField = value;
                    this.RaisePropertyChanged("Passcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ProcessingDB {
            get {
                return this.ProcessingDBField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessingDBField, value) != true)) {
                    this.ProcessingDBField = value;
                    this.RaisePropertyChanged("ProcessingDB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int SendAttempt {
            get {
                return this.SendAttemptField;
            }
            set {
                if ((this.SendAttemptField.Equals(value) != true)) {
                    this.SendAttemptField = value;
                    this.RaisePropertyChanged("SendAttempt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool CDATAWrapping {
            get {
                return this.CDATAWrappingField;
            }
            set {
                if ((this.CDATAWrappingField.Equals(value) != true)) {
                    this.CDATAWrappingField = value;
                    this.RaisePropertyChanged("CDATAWrapping");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.commidea.webservices.com", ConfigurationName="Verifone.CommideaGatewaySoap")]
    public interface CommideaGatewaySoap {
        
        // CODEGEN: Generating message contract since element name Message from namespace https://www.commidea.webservices.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.commidea.webservices.com/ProcessMsg", ReplyAction="*")]
        VerifoneIntegration.Verifone.ProcessMsgResponse ProcessMsg(VerifoneIntegration.Verifone.ProcessMsgRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.commidea.webservices.com/ProcessMsg", ReplyAction="*")]
        System.Threading.Tasks.Task<VerifoneIntegration.Verifone.ProcessMsgResponse> ProcessMsgAsync(VerifoneIntegration.Verifone.ProcessMsgRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessMsgRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessMsg", Namespace="https://www.commidea.webservices.com", Order=0)]
        public VerifoneIntegration.Verifone.ProcessMsgRequestBody Body;
        
        public ProcessMsgRequest() {
        }
        
        public ProcessMsgRequest(VerifoneIntegration.Verifone.ProcessMsgRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.commidea.webservices.com")]
    public partial class ProcessMsgRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VerifoneIntegration.Verifone.Message Message;
        
        public ProcessMsgRequestBody() {
        }
        
        public ProcessMsgRequestBody(VerifoneIntegration.Verifone.Message Message) {
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessMsgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessMsgResponse", Namespace="https://www.commidea.webservices.com", Order=0)]
        public VerifoneIntegration.Verifone.ProcessMsgResponseBody Body;
        
        public ProcessMsgResponse() {
        }
        
        public ProcessMsgResponse(VerifoneIntegration.Verifone.ProcessMsgResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.commidea.webservices.com")]
    public partial class ProcessMsgResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VerifoneIntegration.Verifone.Message ProcessMsgResult;
        
        public ProcessMsgResponseBody() {
        }
        
        public ProcessMsgResponseBody(VerifoneIntegration.Verifone.Message ProcessMsgResult) {
            this.ProcessMsgResult = ProcessMsgResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CommideaGatewaySoapChannel : VerifoneIntegration.Verifone.CommideaGatewaySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommideaGatewaySoapClient : System.ServiceModel.ClientBase<VerifoneIntegration.Verifone.CommideaGatewaySoap>, VerifoneIntegration.Verifone.CommideaGatewaySoap {
        
        public CommideaGatewaySoapClient() {
        }
        
        public CommideaGatewaySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommideaGatewaySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommideaGatewaySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommideaGatewaySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VerifoneIntegration.Verifone.ProcessMsgResponse VerifoneIntegration.Verifone.CommideaGatewaySoap.ProcessMsg(VerifoneIntegration.Verifone.ProcessMsgRequest request) {
            return base.Channel.ProcessMsg(request);
        }
        
        public VerifoneIntegration.Verifone.Message ProcessMsg(VerifoneIntegration.Verifone.Message Message) {
            VerifoneIntegration.Verifone.ProcessMsgRequest inValue = new VerifoneIntegration.Verifone.ProcessMsgRequest();
            inValue.Body = new VerifoneIntegration.Verifone.ProcessMsgRequestBody();
            inValue.Body.Message = Message;
            VerifoneIntegration.Verifone.ProcessMsgResponse retVal = ((VerifoneIntegration.Verifone.CommideaGatewaySoap)(this)).ProcessMsg(inValue);
            return retVal.Body.ProcessMsgResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VerifoneIntegration.Verifone.ProcessMsgResponse> VerifoneIntegration.Verifone.CommideaGatewaySoap.ProcessMsgAsync(VerifoneIntegration.Verifone.ProcessMsgRequest request) {
            return base.Channel.ProcessMsgAsync(request);
        }
        
        public System.Threading.Tasks.Task<VerifoneIntegration.Verifone.ProcessMsgResponse> ProcessMsgAsync(VerifoneIntegration.Verifone.Message Message) {
            VerifoneIntegration.Verifone.ProcessMsgRequest inValue = new VerifoneIntegration.Verifone.ProcessMsgRequest();
            inValue.Body = new VerifoneIntegration.Verifone.ProcessMsgRequestBody();
            inValue.Body.Message = Message;
            return ((VerifoneIntegration.Verifone.CommideaGatewaySoap)(this)).ProcessMsgAsync(inValue);
        }
    }
}
